set(rt_version_major 1)
set(rt_version_minor 0)
set(rt_version ${rt_version_major}.${rt_version_minor})

set(PACKAGE_VERSION ${rt_version})
if("${PACKAGE_FIND_VERSION_MAJOR}" EQUAL "${rt_version_major}")
    if ("${PACKAGE_FIND_VERSION_MINOR}" EQUAL "${rt_version_minor}")
        set(PACKAGE_VERSION_EXACT TRUE)
    elseif("${PACKAGE_FIND_VERSION_MINOR}" LESS "${rt_version_minor}")
        set(PACKAGE_VERSION_COMPATIBLE TRUE)
    else()
        set(PACKAGE_VERSION_UNSUITABLE TRUE)
    endif()
else()
    set(PACKAGE_VERSION_UNSUITABLE TRUE)
endif()
