language: haskell

env:
  global:
  - GHC_VERSION=8.0.2
  matrix:
  - build_with_stack=''
  - build_with_stack=true

before_install:
- export TRAVIS_HASKELL_VERSION=$(travis_ghc_find ${GHC_VERSION})
- source .travis/setenv.sh

install:
- source .travis/install.sh
script:
- jake test
