# Build as:
#   $ stack update
#   $ stack build
#   $ stack exec koka
#
# Note: if stack fails on your platform, try to install the build tools as a package:
#   $ sudo apt install ghc cabal-install haskell-stack
# and invoke stack with an older resolver that matches the system ghc version:
#   $ stack --resolver lts-14 --system-ghc build         # ubuntu 20, ghc 8.6.5
#   $ stack --resolver lts-14 --system-ghc exec koka
# Otherwise, try to use `cabal` directly:
#   $ cabal new-build koka
#   $ cabal new-run koka
# See also <https://github.com/koka-lang/koka#build-notes>.

arch: aarch64

resolver: lts-22.11            # ghc 9.6.4 -- on windows set the codepage to utf-8: `chcp 65001`
# resolver: lts-21.24           # ghc 9.4.8
# resolver: lts-21.0            # ghc 9.4.5
# resolver: lts-19.7            # ghc 9.0.2
# resolver: lts-18.28           # ghc 8.10.7 -- works for M1
# resolver: lts-18.6            # ghc 8.10.4
# resolver: lts-14.27           # ghc 8.6.5
# resolver: lts-9.21            # ghc 8.0.2  -- works for older linux-arm64
# system-ghc: true              # uncomment to use the system installed GHC

packages:
- '.'

extra-deps:
- regex-compat-0.95.2.1          # only needed for koka-test (use 0.95.1.4 for pre lts-21.0)
- json-0.11                      # only needed for koka-test
- isocline-1.0.9
- lsp-2.4.0.0                   # only needed for language server
- lsp-types-2.1.1.0             # only needed for language server
- text-rope-0.2                 # needed for lsp
- co-log-core-0.3.2.1           # needed for lsp
- FloatingHex-0.5               # not really needed, but nice in the language server
- hashable-1.4.3.0
- async-2.2.5

rebuild-ghc-options: true
allow-newer: true

# only for test with resolver 18.17+
flags:
  mintty:
    Win32-2-13-1: false
