/*-----------------------------------------------------------------------------
Copyright 2020-2021, Microsoft Research, Daan Leijen.
This is free software; you can redistribute it and/or modify it under the
terms of the Apache License, Version 2.0. A copy of the License can be
found in the LICENSE file at the root of this distribution.

Used by `stack test` to pre-compil everyting in the `std/toc` module.
-----------------------------------------------------------------------------*/
import toc

fun main() : console () 
  println("done.")

