<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>kkdoc</string>
	</array>
	<key>name</key>
	<string>Koka Documentation</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\s*(={3,}|-{3,})\s*$</string>
			<key>name</key>
			<string>markup.heading</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*""?\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.block.any.html</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.embedded.koka</string>
			<key>end</key>
			<string>^\s*"\s*$</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.block.any.html</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s*""\s*$</string>
					<key>name</key>
					<string>meta.tag.block.any.html</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.koka</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\"\"</string>
			<key>name</key>
			<string>html</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.constant.koka</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(")(:\s*\??([a-z_]\w*|\(,*\)|&lt;\|?&gt;))(")</string>
			<key>name</key>
			<string>source.embedded.koka</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"(?!")</string>
			<key>end</key>
			<string>"(?!")|$</string>
			<key>name</key>
			<string>source.embedded.koka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>"(?=")</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.koka</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*((`{3,}|~{3,})\s*koka\b)(.*)(\n|$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.block.any.html</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.embedded.koka</string>
			<key>end</key>
			<string>^\s*(`{3,}|~{3,})\s*$</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.block.any.html</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s*""\s*$</string>
					<key>name</key>
					<string>meta.tag.block.any.html</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.koka</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*((`{3,}|~{3,})\s*((?!koka\b)\w+\b)?)(.*)(\n|$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.block.any.html</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.embedded</string>
			<key>end</key>
			<string>^\s*(`{3,}|~{3,})\s*</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.block.any.html</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\|//\||\|/\*\|</string>
			<key>name</key>
			<string>source.embedded.koka</string>
		</dict>
		<dict>
			<key>match</key>
			<string>`[^`]*`</string>
			<key>name</key>
			<string>source.embedded.koka</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b#\w+</string>
			<key>name</key>
			<string>meta.tag</string>
		</dict>
		<dict>
			<key>match</key>
			<string>_([^_
]|_\w)*_</string>
			<key>name</key>
			<string>markup.quote</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*([^\*
]|\*\w)*\*</string>
			<key>name</key>
			<string>entity.name.section</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\{[^\n\}]*\}\s*$</string>
			<key>name</key>
			<string>meta.tag.preprocessor.xml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.heading</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.tag.preprocessor.xml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(#+.*?)(\{[^\n\}]*\})\s*$</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(#+.*)$</string>
			<key>name</key>
			<string>markup.heading</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>meta.tag.preprocessor.xml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\[([^\]\n]*)\](?!:)\(([^\)\n]*)\)(\{[^\n\}]*\})?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>meta.tag.preprocessor.xml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\[)([^\]\n]*)(\])(\{[^\n\}]*\})?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\[([^\]\n]*)\](?!:)\s*(\[([^\]\n]*)\])?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.tag.preprocessor.xml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*\[([^\]\n]*)\]:([^\n\{]*)(\{[^\n\}]*\})?\s*$</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.kokadoc</string>
	<key>uuid</key>
	<string>6ff96ac2-ae7c-4c81-9f2a-50f4f62a0d87</string>
</dict>
</plist>
