on:
  workflow_dispatch:   # so we can run the workflow manually as well
  push:
    branches:
      - dev
    tags:
      - 'v*'
  pull_request:
    branches:
      - dev

permissions:
  contents: write

env:
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

name: bundle
jobs:
  build:
    name: Bundle Koka
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macOS 15 is latest for x64, default now is arm64
        # we build on the oldest ubuntu version for better binary compatibility.
        os: [windows-latest, macOS-latest, macos-15-intel, ubuntu-22.04, ubuntu-22.04-arm]

    steps:
      # Checkout: https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true

      # Cache setup for vcpkg (https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-actions-cache)
      # https://github.com/actions/github-script
      - name: Setup vcpkg cache
        uses: actions/github-script@v8
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      # Use a VS shell on Windows (so `cl` is on the PATH): https://github.com/egor-tensin/vs-shell (MIT license)
      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        if: runner.os == 'Windows' && runner.arch == 'X64'
        with:
          arch: x64

      # Set up stack and cache dependencies: https://github.com/freckle/stack-action (MIT license)
      - name: Build compiler
        uses: freckle/stack-action@v5
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          test: false
          stack-build-arguments: ""
          cache-save-always: true

      # Run tests
      - name: Run test suite
        if: runner.os != 'macOS'
        run: |
          stack test

      - name: Run test suite
        if: runner.os == 'macOS'
        env:
          LC_ALL: C
        run: |
          stack test

      # Bundle
      - name: Build libraries
        if: startsWith(github.ref, 'refs/tags/') # only bundle if tagged with a version
        run: |
          stack exec koka -- -e -O2 util/bundle

      # VS code extension
      - name: Package VS code extension
        if: startsWith(github.ref, 'refs/tags/') && runner.os == 'Windows' && runner.arch == 'X64' # only build extension if tagged with a version
        working-directory: support/vscode/koka.language-koka
        run: |
          npm install
          npm run build

      # Create a release: https://github.com/softprops/action-gh-release (MIT license)
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')  # only release if tagged with a version
        with:
          files: |
            bundle/**/*.tar.gz
            support/vscode/koka.language-koka/*.vsix
            util/install.bat
          draft: true
          body_path: util/release.md

      - name: Release install scripts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') && runner.os == 'Linux' && runner.arch == 'X64'  # only release if tagged with a version
        with:
          files: | # Only add install file on Linux to avoid line ending issues: https://github.com/koka-lang/koka/issues/742
            util/install.sh
          draft: true
          body_path: util/release.md

