on:
  workflow_dispatch:   # so we can run the workflow manually as well
    inputs:
      release:
        description: "Release name"
        default: "v3.2.8"
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # Cancel any in-progress runs of this workflow when a new run is triggered on the same ref (branch or tag)

permissions:
  contents: write

env:
  RELEASE: ${{ inputs.release }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

name: Release
jobs:
  build:
    name: Bundle (${{ inputs.release }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        branch: [dev]  # v3.2.8
        # macOS 15 is latest for x64, default now is arm64
        # we build on the oldest ubuntu version for better binary compatibility.
        os: [windows-latest, macOS-latest, macos-15-intel, ubuntu-22.04, ubuntu-22.04-arm]

    steps:
      # Checkout: https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
          fetch-tags: true
          fetch-depth: 0

      # Cache setup for vcpkg (https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-actions-cache)
      # https://github.com/actions/github-script
      - name: Setup vcpkg cache
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      # Use a VS shell on Windows (so `cl` is on the PATH): https://github.com/egor-tensin/vs-shell (MIT license)
      - name: Set up Visual Studio shell (Windows x64)
        uses: egor-tensin/vs-shell@54e4148eac794e4580591c2e0b7750f14b7891fc # v2.2
        if: runner.os == 'Windows' && runner.arch == 'X64'
        with:
          arch: x64

      # Set VCPKG_ROOT on Windows (otherwise it points to the wrong one in the VS install)
      - name: Set VCPKG_ROOT (Windows)
        if: runner.os == 'Windows'
        run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" >> $env:GITHUB_ENV


      # Set up stack and cache dependencies: https://github.com/freckle/stack-action (MIT license)
      - name: Build compiler
        uses: freckle/stack-action@c5b62aa4c722658775d1c53d501a21bca1d28c5a #v5.7.29
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          test: false
          stack-build-arguments: ""
          cache-save-always: true

      # Bundle
      - name: Build libraries
        run: |
          stack exec koka -- -e -O2 util/bundle

      # VS code extension
      - name: Package VS code extension (Windows x64)
        if: runner.os == 'Windows' && runner.arch == 'X64' # only build extension if tagged with a version
        working-directory: support/vscode/koka.language-koka
        run: |
          npm install
          npm run build

      # Create a release: https://github.com/softprops/action-gh-release (MIT license)
      - name: Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        if: env.RELEASE != '' && env.RELEASE != 'no'
        with:
          name: ${{ env.RELEASE }}
          files: |
            bundle/**/*.tar.gz
            support/vscode/koka.language-koka/*.vsix
            util/install.bat
          draft: true
          body_path: util/release.md

      - name: Release install scripts
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        if: env.RELEASE != '' && env.RELEASE != 'no' && runner.os == 'Linux' && runner.arch == 'X64'  # only release if tagged with a version
        with:
          name: ${{ env.RELEASE }}
          files: | # Only add install file on Linux to avoid line ending issues: https://github.com/koka-lang/koka/issues/742
            util/install.sh
          draft: true
          body_path: util/release.md

